# Generated by Django 5.0.4 on 2024-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
