# Generated by Django 5.0.4 on 2024-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile_images/profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
