# Generated by Django 5.0.4 on 2024-04-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cart_countinstock_cart_image_cart_name_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_images/product_sample.jpg', null=True, upload_to='product_images/'),
        ),
    ]
